### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by joajfreitas** [pineman/services#1]
![https://miro.medium.com/max/2048/1*K_EttppoSnzla46m-ZkscA.jpeg](https://miro.medium.com/max/2048/1*K_EttppoSnzla46m-ZkscA.jpeg)

**Comment by pineman** [comment]
seu... well played, caí no memenetes

**Comment by joajfreitas** [comment]
This is a public space, my friend.

And what about that sweet email workflow for issues, how does that work?
